### ISSUE TITLE
Traning dataset

### ISSUE THREAD

**Issue by Alvacv** [TaoHuang95/DGSMP#3]
The paper said "Following the procedure in TSANet [22], the CAVE dataset is used for network training." If I use the dataset of TSANet which is composed of 205 HSIs of spatial size 1024×1024 to train the model, the result is very bad. And I find that the number of training scenes in training code is 30. Therefore I am confused about training dataset of this paper.

**Comment by TaoHuang95** [comment]
We adopted the same spectral interpolation operation as TSANet on the simulation data to acquire HSIs with 28 channels. Since the size of the training samples is 96 x 96 in our method, we have not used the concatenation operation for data augmentation.
You can tell me your email, and I send the training data to you.
Later, I will upload the training data.

**Comment by Alvacv** [comment]
Thank you for replay. This is my email: xinranqin@foxmail.com. I will treasure it

**Comment by TaoHuang95** [comment]
OK. I have sent the training data to you.
